/*
 * serializacion_nucleo_cpu.h
 *
 *  Created on: 22/5/2016
 *      Author: utnso
 */

#ifndef SERIALIZACION_NUCLEO_CPU_H_
#define SERIALIZACION_NUCLEO_CPU_H_

// Funciones CPU - Nucleo
#define MENSAJE_HANDSHAKE 0
#define MENSAJE_OBTENER_VALOR_COMPARTIDA 1
#define MENSAJE_ASIGNAR_VARIABLE_COMPARTIDA 2
#define MENSAJE_IMPRIMIR 3
#define MENSAJE_IMPRIMIR_TEXTO 4
#define MENSAJE_ENTRADA_SALIDA 5
#define MENSAJE_WAIT 6
#define MENSAJE_SIGNAL 7
#define MENSAJE_QUANTUM 8
#define MENSAJE_PROGRAMA_FINALIZADO 9
// Respuestas OK
#define RESPUESTA_OBTENER_VALOR_COMPARTIDA 11
#define RESPUESTA_ASIGNAR_VARIABLE_COMPARTIDA 12
#define RESPUESTA_IMPRIMIR 13
#define RESPUESTA_IMPRIMIR_TEXTO 14
#define RESPUESTA_ENTRADA_SALIDA 15
#define RESPUESTA_WAIT 16
#define RESPUESTA_SIGNAL 17
#define RESPUESTA_QUANTUM 18
#define RESPUESTA_PROGRAMA_FINALIZADO 19
// Respuestas Error
#define ERROR_OBTENER_VALOR_COMPARTIDA 21
#define ERROR_ASIGNAR_VARIABLE_COMPARTIDA 22
#define ERROR_IMPRIMIR 23
#define ERROR_IMPRIMIR_TEXTO 24
#define ERROR_ENTRADA_SALIDA 25
#define ERROR_WAIT 26
#define ERROR_SIGNAL 27
#define ERROR_QUANTUM 28
#define ERROR_PROGRAMA_FINALIZADO 29

// Funciones Nucleo - CPU
#define MENSAJE_PCB_NUCLEO 1
#define MENSAJE_MATAR 2
// Respuestas OK
#define RESPUESTA_PCB_NUCLEO 11
#define RESPUESTA_MATAR 12
// Respuestas Error
#define ERROR_PCB_NUCLEO 21
#define ERROR_MATAR 22

#endif /* SERIALIZACION_NUCLEO_CPU_H_ */
