#! /bin/bash
echo Compilando Consola...
gcc -Wall -o consola_ejecutable src/consola.c src/serializacion_consola_nucleo.c -lcomunicaciones -lserializacion -lpthread -lcommons
echo Levantando Consola...
./consola_ejecutable
