#! /bin/bash
echo Compilando CPU...
gcc -Wall -o cpu_ejecutable src/cpu.c src/funciones_comunes.c src/primitivas_ansisop.c src/serializaciones_cpu.c src/comunicaciones_cpu.c -lcomunicaciones -lserializacion -lpthread -lcommons -lparser-ansisop
echo Levantando CPU...
sudo ./cpu_ejecutable