#! /bin/bash
echo Compilando SWAP...
gcc -Wall -o swap_ejecutable src/swap.c src/utilidades_swap.c src/serializacion_swap_umc.c -lcomunicaciones -lserializacion -lpthread -lcommons
echo Levantando SWAP...
./swap_ejecutable
