/*
 * mensajes_cpu.h
 *
 *  Created on: 18/6/2016
 *      Author: utnso
 */

#ifndef MENSAJES_CPU_H_
#define MENSAJES_CPU_H_

// Funciones globales de comunicacion
#define MENSAJE_HANDSHAKE 0
#define RESPUESTA_HANDSHAKE 10
#define ERROR_HANDSHAKE 20

// Funciones CPU - UMC
#define MENSAJE_LEER_PAGINA 1
#define MENSAJE_ESCRIBIR_PAGINA 2
#define MENSAJE_CAMBIO_PROCESO_ACTIVO 5
// Respuestas OK
#define RESPUESTA_LEER_PAGINA 11
#define RESPUESTA_ESCRIBIR_PAGINA 12
#define RESPUESTA_CAMBIO_PROCESO_ACTIVO 15
// Respuestas Error
#define ERROR_LEER_PAGINA 21
#define ERROR_ESCRIBIR_PAGINA 22
#define ERROR_CAMBIO_PROCESO_ACTIVO 25

// Funciones CPU - Nucleo
#define MENSAJE_LEER_COMPARTIDA 1
#define MENSAJE_ESCRIBIR_COMPARTIDA 2
#define MENSAJE_IMPRIMIR 3
#define MENSAJE_IMPRIMIR_TEXTO 4
#define MENSAJE_ENTRADA_SALIDA 5
#define MENSAJE_WAIT 6
#define MENSAJE_SIGNAL 7
#define MENSAJE_QUANTUM 8
#define MENSAJE_PROGRAMA_FINALIZADO 9
#define MENSAJE_EXCEPCION_UMC 30
#define MENSAJE_TEXTO_EXCEPCION 31
#define MENSAJE_MATAR_CPU 32
#define MENSAJE_ENTRADA_SALIDA_PCB 35
#define MENSAJE_WAIT_PCB 36
#define MENSAJE_DESCONEXION_CPU 50
#define MENSAJE_SIGINT 58
// Respuestas OK
#define RESPUESTA_LEER_COMPARTIDA 11
#define RESPUESTA_ESCRIBIR_COMPARTIDA 12
#define RESPUESTA_IMPRIMIR 13
#define RESPUESTA_IMPRIMIR_TEXTO 14
#define RESPUESTA_ENTRADA_SALIDA 15
#define RESPUESTA_WAIT 16 // Respuesta de 16, me bloqueo
#define RESPUESTA_PCB 56 // Cuando recibo un 16, respondo con un 56 y mando PCB
#define RESPUESTA_PCB_OK 66 // Recibio el PCB correctamente
#define RESPUESTA_SEGUI_RAFAGA 86 // Sigo con mi rafaga actual
#define RESPUESTA_SIGNAL 17
#define RESPUESTA_QUANTUM 18
#define RESPUESTA_PROGRAMA_FINALIZADO 19
#define RESPUESTA_EXCEPCION_UMC 40
#define RESPUESTA_TEXTO_EXCEPCION 41
#define RESPUESTA_MATAR_CPU 42
// Respuestas Error
#define ERROR_LEER_COMPARTIDA 21
#define ERROR_ESCRIBIR_COMPARTIDA 22
#define ERROR_IMPRIMIR 23
#define ERROR_IMPRIMIR_TEXTO 24
#define ERROR_ENTRADA_SALIDA 25
#define ERROR_WAIT 26
#define ERROR_SIGNAL 27
#define ERROR_QUANTUM 28
#define ERROR_PROGRAMA_FINALIZADO 29
#define ERROR_EXCEPCION_UMC 50
#define ERROR_RESPUESTA_PCB 76
#define ERROR_TEXTO_EXCEPCION 51
#define ERROR_MATAR_CPU 52

// Funciones Nucleo - CPU
#define MENSAJE_PCB_NUCLEO 1
#define MENSAJE_MATAR 2
// Respuestas OK
#define RESPUESTA_PCB_NUCLEO 11
#define RESPUESTA_MATAR 12
// Respuestas Error
#define ERROR_PCB_NUCLEO 21
#define ERROR_MATAR 22

// Defines varios
#define VACIO 0
#define FIN_QUANTUM 0
#define NEW 0

#endif /* MENSAJES_CPU_H_ */
